# Generated by Django 4.1.7 on 2023-03-18 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=200)),
                ('deadline', models.DateField()),
                ('assigned_to', models.CharField(choices=[('myself', 'Myself'), ('other_guy', 'Other_guy')], max_length=20)),
            ],
        ),
    ]
